const products = [
  //jeans
    {
        id: '1',
        title: 'Jeans 01',
        image:'./css/img/jeans/jean1.jpg',
        categori: 'Jeans',
        price: 45,
    },
    {
        id: '2',
        title: 'Jeans 02',
        image:'./css/img/jeans/jean2.jpg',
        categori: 'Jeans',
        price: 63,
    },
    {
        id: '3',
        title: 'Jeans 03',
        image:'./css/img/jeans/jean3.jpg',
        categori: 'Jeans',
        price: 38,
    },
    {
        id: '4',
        title: 'Jeans 04',
        image:'./css/img/jeans/jean4.jpg',
        categori: 'Jeans',
        price: 75,
    },
    {
        id: '5',
        title: 'Jeans 05',
        image:'./css/img/jeans/jean5.jpg',
        categori: 'Jeans',
        price: 65,
    },
    {
        id: '6',
        title: 'Jeans 06',
        image:'./css/img/jeans/jean6.jpg',
        categori: 'Jeans',
        price: 95,
    },
    //vestido
    {
        id: '7',
        title: 'Dress 01',
        image:'./css/img/drees/vestido1.jpg',
        categori: 'Dress',
        price: 49,
    },
    {
        id: '8',
        title: 'Dress 02',
        image:'./css/img/drees/vestido2.jpg',
        categori: 'Dress',
        price: 59,
    },
    {
        id: '9',
        title: 'Dress 03',
        image:'./css/img/drees/vestido3.jpg',
        categori: 'Dress',
        price: 89,
    },
    {
        id: '10',
        title: 'Dress 04',
        image:'./css/img/drees/vestido4.jpg',
        categori: 'Dress',
        price: 69,
    },
    {
        id: '11',
        title: 'Dress 05',
        image:'./css/img/drees/vestido5.jpg',
        categori: 'Dress',
        price: 149,
    },
    {
        id: '12',
        title: 'Dress 06',
        image:'./css/img/drees/vestido6.jpg',
        categori: 'Dress',
        price: 135,
    },
    //accesorios
    {
        id: '13',
        title: 'Bag 01',
        image:'./css/img/accesorios/cartera1.jpg',
        categori: 'Accesories',
        price: 109,
    },
    {
        id: '14',
        title: 'Bag 02',
        image:'./css/img/accesorios/cartera2.jpg',
        categori: 'Accesories',
        price: 95,
    },
    {
        id: '15',
        title: 'Sunglasses 01',
        image:'./css/img/accesorios/lentes1.jpg',
        categori: 'Accesories',
        price: 29,
    },
    {
        id: '16',
        title: 'Sunglasses 02',
        image:'./css/img/accesorios/lentes2.jpg',
        categori: 'Accesories',
        price: 34,
    },
    {
        id: '17',
        title: 'Shoes 01',
        image:'./css/img/accesorios/zapatos1.jpg',
        categori: 'Accesories',
        price: 78,
    },
    {
        id: '18',
        title: 'Shoes 02',
        image:'./css/img/accesorios/zapatos2.jpg',
        categori: 'Accesories',
        price: 159,
    },
    //camperas
    {
        id: '19',
        title: 'Jackets 01',
        image:'./css/img/jackets/campera1.jpg',
        categori: 'Jackets',
        price: 149,
    },
    {
        id: '20',
        title: 'Jackets 02',
        image:'./css/img/jackets/campera2.jpg',
        categori: 'Jackets',
        price: 109,
    },
    {
        id: '21',
        title: 'Jackets 03',
        image:'./css/img/jackets/campera3.jpg',
        categori: 'Jackets',
        price: 95,
    },
    {
        id: '22',
        title: 'Jackets 04',
        image:'./css/img/jackets/campera4.jpg',
        categori: 'Jackets',
        price: 129,
    },
    {
        id: '23',
        title: 'Jackets 05',
        image:'./css/img/jackets/campera5.jpg',
        categori: 'Jackets',
        price: 134,
    },
    {
        id: '24',
        title: 'Jackets 06',
        image:'./css/img/jackets/campera6.jpg',
        categori: 'Jackets',
        price: 178,
    },
    //camisas
    {
        id: '25',
        title: 'Shirt 01',
        image:'./css/img/shirt/camisa1.jpg',
        categori: 'Shirt',
        price: 63,
    },
    {
        id: '26',
        title: 'Shirt 02',
        image:'./css/img/shirt/camisa2.jpg',
        categori: 'Shirt',
        price: 83,
    },
    {
        id: '27',
        title: 'Shirt 03',
        image:'./css/img/shirt/camisa3.jpg',
        categori: 'Shirt',
        price: 76,
    },
    {
        id: '28',
        title: 'Shirt 04',
        image:'./css/img/shirt/camisa4.jpg',
        categori: 'Shirt',
        price: 58,
    },
    {
        id: '29',
        title: 'Shirt 05',
        image:'./css/img/shirt/camisa5.jpg',
        categori: 'Shirt',
        price: 54,
    },
    {
        id: '30',
        title: 'Shirt 06',
        image:'./css/img/shirt/camisa6.jpg',
        categori: 'Shirt',
        price: 52,
    },
    //Remerass
    {
        id: '31',
        title: 'T-shirt 01',
        image:'./css/img/T-shirt/remera1.jpg',
        categori: 'T-Shirt',
        price: 16,
    },
    {
        id: '32',
        title: 'T-shirt 02',
        image:'./css/img/T-shirt/remera2.jpg',
        categori: 'T-Shirt',
        price: 16,
    },
    {
        id: '33',
        title: 'T-shirt 03',
        image:'./css/img/T-shirt/remera3.jpg',
        categori: 'T-Shirt',
        price: 16,
    },
    {
        id: '34',
        title: 'T-shirt 04',
        image:'./css/img/T-shirt/remera4.jpg',
        categori: 'T-Shirt',
        price: 16,
    },
    {
        id: '35',
        title: 'T-shirt 05',
        image:'./css/img/T-shirt/remera5.jpg',
        categori: 'T-Shirt',
        price: 16,
    },
    {
        id: '36',
        title: 'T-shirt 06',
        image:'./css/img/T-shirt/remera6.jpg',
        categori: 'T-Shirt',
        price: 16,
    },
    //Nuevos Productos
    {
        id: '37',
        title: 'T-shirt 07',
        image:'./css/img/new/nuevo1.jpg',
        categori: 'New',
        price: 16,
    },
    {
        id: '38',
        title: 'T-shirt 08',
        image:'./css/img/new/nuevo2.jpg',
        categori: 'New',
        price: 16,
    },
    {
        id: '39',
        title: 'Jeans 07',
        image:'./css/img/new/nuevo3.jpg',
        categori: 'New',
        price: 86,
    },
    {
        id: '40',
        title: 'Jeans 08',
        image:'./css/img/new/nuevo4.jpg',
        categori: 'New',
        price: 96,
    },
    {
        id: '41',
        title: 'Shirt 07',
        image:'./css/img/new/nuevo5.jpg',
        categori: 'New',
        price: 56,
    },
    {
        id: '42',
        title: 'Sport-Shoes 01',
        image:'./css/img/new/nuevo6.jpg',
        categori: 'New',
        price: 95,
    },
    {
        id: '43',
        title: 'Sport-Shoes 02',
        image:'./css/img/new/nuevo7.jpg',
        categori: 'New',
        price: 142,
    },
    {
        id: '44',
        title: 'Jackets 07',
        image:'./css/img/new/nuevo8.jpg',
        categori: 'New',
        price: 86,
    },
    //ofertas
    {
        id: '45',
        title: 'Jackets 09',
        image:'./css/img/sale/sale1.jpg',
        categori: 'Sale',
        price: 56,
    },
    {
        id: '46',
        title: 'Sport-Shoes 03',
        image:'./css/img/sale/sale2.jpg',
        categori: 'Sale',
        price: 36,
    },
    {
        id: '47',
        title: 'Sweters',
        image:'./css/img/sale/sale3.jpg',
        categori: 'Sale',
        price: 46,
    },
]